//------------------product-------------------------------
###
GET http://localhost:3000/products HTTP/1.1

###

POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "Telewizor",
    "description": "Telewizor plazmowy",
    "price": 5000,
    "category": "60c1ae19f3f0dc43f5a044a5"
}


###
PUT http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "id": "60ae9ecd08037f08c4b74c0e",
    "name": "Kamera 5",
    "description": "Telewizor plazmowy",
    "price": 15000
}

###
DELETE http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "id": "60c1ae28f3f0dc43f5a044a6"
}


//------------------Category------------------------------
###
GET http://localhost:3000/categories HTTP/1.1

###
POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "Sprzęt RTV"
}

###
PUT http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "id": "60c1ba16b5055c6231ad7972",
    "name": "Sprzęt AGD"
}

###
DELETE http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "id": "60c1ae19f3f0dc43f5a044a5"
}